<?php
declare(strict_types=1);

namespace Opus\Scaffold;

/**
 * Scaffold plan for an OPUS application module.
 *
 * Contract:
 * - module inherits the common application layer;
 * - module carries only business resources and overrides;
 * - no page is created at module creation time.
 */
final class ModuleScaffoldPlan implements ScaffoldPlanInterface
{
    private function __construct(
        private readonly string $siteId,
        private readonly string $moduleName
    ) {
    }

    public static function forModule(string $siteId, string $moduleName): self
    {
        return new self($siteId, $moduleName);
    }

    public function rootRelativePath(): string
    {
        return 'sites/' . $this->siteId . '/application/modules/' . $this->moduleName;
    }

    /**
     * @return list<ScaffoldEntry>
     */
    public function entries(): array
    {
        $root = $this->rootRelativePath();

        $directories = [
            "{$root}/acl",
            "{$root}/helpers",
            "{$root}/assets",
            "{$root}/javascript",
            "{$root}/local",
            "{$root}/models",
            "{$root}/services",
            "{$root}/controllers",
            "{$root}/view-models",
            "{$root}/views",
            "{$root}/templates/pages",
            "{$root}/templates/partials",
            "{$root}/templates/components",
        ];

        $entries = array_map(static fn (string $directory): ScaffoldEntry => ScaffoldEntry::directory($directory), $directories);

        $entries[] = ScaffoldEntry::file("{$root}/README.md", $this->readmeContent());
        $entries[] = ScaffoldEntry::file("{$root}/module.json", $this->json([
            'module_id' => $this->moduleName,
            'site_id' => $this->siteId,
            'contract' => 'OPUS_APPLICATION_MODULE_V1',
            'inherits_common_layer' => true,
            'external_dependencies_allowed' => false,
            'html_rendering' => 'score-template',
            'created_by' => 'composer opus:create-module',
        ]));
        $entries[] = ScaffoldEntry::file("{$root}/templates/layout.score", $this->moduleLayoutScore());

        return $entries;
    }

    private function readmeContent(): string
    {
        return "# {$this->moduleName}\n\nOPUS application module scaffold generated by `composer opus:create-module`.\n\n## Contract\n\n- This module inherits the application common layer.\n- This module carries only its business logic, overrides and resources.\n- Pages must be added later through a dedicated page/route contract.\n- Any HTML representation must use `.score` templates.\n";
    }

    private function moduleLayoutScore(): string
    {
        return "<section class=\"module module-{{ module.id }}\">\n  {{ content }}\n</section>\n";
    }

    /**
     * @param array<string, mixed> $data
     */
    private function json(array $data): string
    {
        return (string) json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n";
    }
}
