<?php

declare(strict_types=1);

namespace Opus\Acl;

use ASAP\RefBook\Attribute\OpusRefBookClass;
use ASAP\RefBook\Attribute\OpusRefBookMethod;
use ASAP\RefBook\Contract\RefBookInspectableInterface;

/*
 * OPUS_REFBOOK:
 *   domain: ACL
 *   role: Class AccessDecision belongs to the ACL Opus framework domain.
 *   contract:
 *     - keeps responsibility limited to the ACL domain
 *     - exposes explicit behavior for the RefBook extractor
 *     - must not rely on silent fallback behavior
 *   examples:
 *     - acl-overview
 *   diagrams:
 *     - acl-runtime
 * END_OPUS_REFBOOK
 */
/**
 * PUBLIC DTO
 *
 * Role:
 *   Represents an ACL decision.
 *
 * Responsibility:
 *   Carry allow/deny result and explicit reason.
 *
 * Contract:
 *   Authorization result must be inspectable.
 *
 * @package ASAP\Acl
 */
#[OpusRefBookClass(
    domain: 'ACL',
    role: 'Represent one explicit ACL access decision',
    responsibility: 'Carry the allow/deny outcome and stable reason produced by the ACL decision engine.',
    contracts: [
        'The decision outcome is explicit and inspectable.',
        'The reason describes why access was allowed or denied.',
        'Decision objects do not evaluate rules or mutate ACL state.',
    ],
    examples: ['acl-overview'],
    diagrams: ['acl-runtime'],
    introducedIn: 'P112Q3E2'
)]
final class AccessDecision implements RefBookInspectableInterface
{
    private bool $allowed;
    private string $reason;

    #[OpusRefBookMethod(
        role: 'Expose the RefBook domain for ACL decisions',
        behavior: 'Returns the stable RefBook domain used by scanners, snapshots and OPUS_REF_BOOK renderers.',
        preconditions: ['none'],
        postconditions: ['The returned domain is ACL.'],
        sideEffects: ['none'],
        errors: ['none'],
        testRefs: ['tests/Contract/RefBookAclMetadataContractTest.php'],
        examples: ['acl-refbook-domain'],
        diagrams: ['acl-runtime'],
        introducedIn: 'P112Q3E2'
    )]
    public static function refBookDomain(): string
    {
        return 'ACL';
    }

    /**
     * PUBLIC API
     *
     * @param bool $allowed Decision result.
     * @param string $reason Explicit decision reason.
     */
    #[OpusRefBookMethod(
        role: 'Create an immutable ACL access decision',
        behavior: 'Stores an allow/deny boolean and explicit reason generated by AccessControl.',
        preconditions: ['The caller provides an explicit outcome and reason.'],
        postconditions: ['The outcome and reason are available for inspection.'],
        sideEffects: ['none'],
        errors: ['none'],
        testRefs: ['tests/Contract/RefBookAclMetadataContractTest.php'],
        examples: ['acl-overview'],
        diagrams: ['acl-runtime'],
        introducedIn: 'P112Q3E2'
    )]
    public function __construct(bool $allowed, string $reason)
    {
        $this->allowed = $allowed;
        $this->reason = $reason;
    }

    /**
     * PUBLIC API
     *
     * @return bool True when access is allowed.
     */
    #[OpusRefBookMethod(
        role: 'Expose whether access is allowed',
        behavior: 'Returns the immutable boolean decision outcome.',
        preconditions: ['The decision has been constructed.'],
        postconditions: ['The decision object is not modified.'],
        sideEffects: ['none'],
        errors: ['none'],
        testRefs: ['tests/Contract/RefBookAclMetadataContractTest.php'],
        examples: ['acl-overview'],
        diagrams: ['acl-runtime'],
        introducedIn: 'P112Q3E2'
    )]
    public function allowed(): bool
    {
        return $this->allowed;
    }

    /**
     * PUBLIC API
     *
     * @return string Explicit decision reason.
     */
    #[OpusRefBookMethod(
        role: 'Expose the explicit ACL decision reason',
        behavior: 'Returns the immutable reason string associated with the allow or deny outcome.',
        preconditions: ['The decision has been constructed.'],
        postconditions: ['The decision object is not modified.'],
        sideEffects: ['none'],
        errors: ['none'],
        testRefs: ['tests/Contract/RefBookAclMetadataContractTest.php'],
        examples: ['acl-overview'],
        diagrams: ['acl-runtime'],
        introducedIn: 'P112Q3E2'
    )]
    public function reason(): string
    {
        return $this->reason;
    }
}
