<?php

declare(strict_types=1);

return [
    [
        'id' => 'autoload_cache',
        'label' => 'Official Opus autoloader classmap cache',
        'technical_recipe' => 'autoload_cache',
        'life_recipe' => 'life_http_mail_robot',
        'docs' => ['DOC/P112Q2K1_OPUS_AUTOLOADER_CACHE_CONTRACT.md'],
        'paths' => ['framework/Opus/Autoload', 'tools/autoload/opus_autoload_cache_build.php', 'tools/recipes/recipes/AutoloadCacheRecipe.php'],
    ],
    [
        'id' => 'core_autoload',
        'label' => 'Opus core autoload and HTTP primitives',
        'technical_recipe' => 'core_autoload',
        'life_recipe' => 'life_public_site',
        'docs' => ['README.md', 'DOC/ARCHITECTURE.md'],
        'paths' => ['framework/Opus/Core', 'framework/Opus/Http'],
    ],
    [
        'id' => 'database_multi_provider',
        'label' => 'Database provider and multi-BDD contract',
        'technical_recipe' => 'database',
        'life_recipe' => 'life_database',
        'docs' => ['DOC/P112Q2H_OPUS_DATABASE_PROVIDER_SITE_CONFIG_FOUNDATION.md'],
        'paths' => ['framework/Opus/Database'],
    ],
    [
        'id' => 'fsm',
        'label' => 'Finite state machine',
        'technical_recipe' => 'fsm',
        'life_recipe' => 'life_lstsar_background',
        'docs' => ['DOC/FSM.md'],
        'paths' => ['framework/Opus/Fsm'],
    ],
    [
        'id' => 'acl',
        'label' => 'Access control',
        'technical_recipe' => 'acl',
        'life_recipe' => 'life_acl_access',
        'docs' => ['DOC/ACL.md'],
        'paths' => ['framework/Opus/Acl'],
    ],
    [
        'id' => 'i18n',
        'label' => 'I18N and plurals',
        'technical_recipe' => 'i18n',
        'life_recipe' => 'life_i18n',
        'docs' => ['DOC/P112D4A_OPUS_MASS_CORE_I18N_PORT.md'],
        'paths' => ['framework/Opus/I18n', 'resources/i18n'],
    ],
    [
        'id' => 'routing',
        'label' => 'Routing and site definitions',
        'technical_recipe' => 'routing',
        'life_recipe' => 'life_http_mail_robot',
        'docs' => ['DOC/ROUTER_ATTRIBUTE_COMPILER.md'],
        'paths' => ['framework/Opus/Routing', 'framework/Opus/Site'],
    ],
    [
        'id' => 'template',
        'label' => 'Template and renderer',
        'technical_recipe' => 'template',
        'life_recipe' => 'life_http_mail_robot',
        'docs' => ['DOC/TEMPLATE_ADAPTERS.md'],
        'paths' => ['framework/Opus/Template', 'framework/Opus/Renderer'],
    ],
    [
        'id' => 'mail',
        'label' => 'Mail boundary and robot mailbox',
        'technical_recipe' => 'mail',
        'life_recipe' => 'life_http_mail_robot',
        'docs' => ['DOC/P112Q2J2_OPUS_GLOBAL_EVOLUTIVE_HTTP_MAIL_LIFE_RECIPE.md', 'DOC/P112Q2J4_OPUS_REAL_MAILPIT_LIVE_RECIPE.md'],
        'paths' => ['framework/Opus/Mail', 'tools/recipes/recipes/MailRecipe.php'],
    ],
    [
        'id' => 'lstsar',
        'label' => 'LSTSAR background pipeline',
        'technical_recipe' => 'lstsa',
        'life_recipe' => 'life_lstsar_background',
        'docs' => ['DOC/P112Q2I5_OPUS_Lstsa_FSM_BACKGROUND_STAGING.md'],
        'paths' => ['framework/Opus/Lstsa'],
    ],
    [
        'id' => 'real_mailpit_life_recipe',
        'label' => 'Real Mailpit SMTP/API life recipe with visible dashboard evidence',
        'technical_recipe' => 'mail',
        'life_recipe' => 'life_http_mail_robot',
        'docs' => ['DOC/P112Q2J4_OPUS_REAL_MAILPIT_LIVE_RECIPE.md'],
        'paths' => ['tools/recipes/recipes/MailRecipe.php', 'tools/recipes/life/scenarios/HttpMailLifeRobotScenario.php'],
    ],
    [
        'id' => 'live_movie_dashboard',
        'label' => 'Visible live movie dashboard for global life recipe',
        'technical_recipe' => 'feature_manifest',
        'life_recipe' => 'life_http_mail_robot',
        'docs' => ['DOC/P112Q2J3_OPUS_RECIPE_LIVE_MOVIE_DASHBOARD.md', 'DOC/P112Q2J4_OPUS_REAL_MAILPIT_LIVE_RECIPE.md'],
        'paths' => ['tools/recipes/life/scenarios/HttpMailLifeRobotScenario.php', 'tools/recipes/RUN_OPUS_FULL_RECIPE_VISIBLE_BROWSER.cmd'],
    ],

    [
        'id' => 'real_features_recipe_binding',
        'label' => 'Real OPUS_REF_BOOK feature binding and historical recipe anti-regression',
        'technical_recipe' => 'real_feature_binding',
        'life_recipe' => 'life_http_mail_robot',
        'docs' => ['DOC/P112Q2K_OPUS_REAL_FEATURES_RECIPE_BINDING.md'],
        'paths' => ['tools/recipes/recipes/RealFeatureBindingRecipe.php', 'tools/recipes/manifest/opus_feature_manifest.php'],
    ],
    [
        'id' => 'global_recipe_suite',
        'label' => 'Global technical and life recipe suite',
        'technical_recipe' => 'feature_manifest',
        'life_recipe' => 'life_http_mail_robot',
        'docs' => ['DOC/P112Q2J_OPUS_GLOBAL_RECIPE_SUITE.md', 'DOC/P112Q2J2_OPUS_GLOBAL_EVOLUTIVE_HTTP_MAIL_LIFE_RECIPE.md', 'DOC/P112Q2J3_OPUS_RECIPE_LIVE_MOVIE_DASHBOARD.md', 'DOC/P112Q2J4_OPUS_REAL_MAILPIT_LIVE_RECIPE.md'],
        'paths' => ['tools/recipes'],
    ],
];
