<?php
declare(strict_types=1);

$siteRoot = dirname(__DIR__);
$routesFile = $siteRoot . '/config/routes.json';
$routesConfig = json_decode((string) file_get_contents($routesFile), true);
if (!is_array($routesConfig) || !isset($routesConfig['routes']) || !is_array($routesConfig['routes'])) {
    http_response_code(500);
    echo 'OPUS_GENERATED_ROUTES_INVALID';
    exit;
}

$path = parse_url((string) ($_SERVER['REQUEST_URI'] ?? '/'), PHP_URL_PATH);
$path = is_string($path) ? rawurldecode($path) : '/';
$path = '/' . trim($path, '/');
$route = null;
foreach ($routesConfig['routes'] as $candidate) {
    if (is_array($candidate) && ($candidate['path'] ?? null) === $path) {
        $route = $candidate;
        break;
    }
}
if (!is_array($route)) {
    http_response_code(404);
    echo 'OPUS_GENERATED_ROUTE_NOT_FOUND';
    exit;
}

$controller = (string) ($route['controller'] ?? 'home');
if (!preg_match('/^[a-z0-9][a-z0-9_-]*$/', $controller)) {
    http_response_code(500);
    echo 'OPUS_GENERATED_CONTROLLER_INVALID';
    exit;
}

$viewFile = $siteRoot . '/application/' . $controller . '/views/index.php';
$page = is_file($viewFile) ? require $viewFile : ['title' => $controller, 'subtitle' => 'Generated by OWASYS'];
if (!is_array($page)) {
    $page = ['title' => $controller, 'subtitle' => 'Generated by OWASYS'];
}

$h = static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');

echo '<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' . $h((string) ($page['title'] ?? $controller)) . '</title><link rel="stylesheet" href="/asset/css/default.css"><link rel="stylesheet" href="/asset/themes/starter/css/theme.css"></head><body class="opus-generated-site"><main class="opus-shell"><article class="opus-card"><h1>' . $h((string) ($page['title'] ?? $controller)) . '</h1><p>' . $h((string) ($page['subtitle'] ?? 'Generated by OWASYS')) . '</p></article></main><script src="/asset/js/default.js"></script><script src="/asset/themes/starter/js/theme.js"></script></body></html>';