#!/usr/bin/env python3
"""
P6A_REMOVE_LEGACY_RUNTIME_BOUNDARY

Controlled migration to remove the OPUS runtime dependency on Opus/Legacy.

Contract:
- no silent fallback;
- Composer remains the only loader for www/index.php;
- OPUS_Application is kept unchanged as a runtime class and moved out of Opus/Legacy;
- Opus/Legacy is removed only after runtime references are rewritten;
- Composer autoload must be regenerated by the operator after this migration.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

PATCH_ID = "P6A_REMOVE_LEGACY_RUNTIME_BOUNDARY"
ROOT = Path.cwd()

LEGACY_AUTOLOADER = ROOT / "Opus/Legacy/Autoload/autoloader.class.php"
LEGACY_APPLICATION = ROOT / "Opus/Legacy/Application/Application.class.php"
RUNTIME_APPLICATION = ROOT / "Opus/Runtime/Application.php"
WWW_INDEX = ROOT / "www/index.php"
P5B_SMOKE = ROOT / "tools/smokes/smoke_p5b_current_runtime_layout.php"
P5E_AUDIT = ROOT / "tools/audits/audit_p5e_bootstrap_readiness.py"
P5G_AUDIT = ROOT / "tools/audits/audit_p5g_legacy_autoloader_bootstrap_bridge.py"
P5H_AUDIT = ROOT / "tools/audits/audit_p5h_bootstrap_move_design.py"


def fail(message: str) -> None:
    raise RuntimeError(f"{PATCH_ID}: {message}")


def read(path: Path) -> str:
    if not path.is_file():
        fail(f"required file missing: {path.as_posix()}")
    return path.read_text(encoding="utf-8", errors="ignore")


def write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8", newline="\n")


def replace_once(content: str, old: str, new: str, label: str) -> str:
    if old not in content:
        if new in content:
            print(f"ALREADY_PATCHED={label}")
            return content
        fail(f"token not found for {label}")
    print(f"PATCHED={label}")
    return content.replace(old, new, 1)


def regex_replace_once(content: str, pattern: str, new: str, label: str) -> str:
    updated, count = re.subn(pattern, new, content, count=1, flags=re.S)
    if count == 0:
        if new.strip() in content:
            print(f"ALREADY_PATCHED={label}")
            return content
        fail(f"pattern not found for {label}")
    print(f"PATCHED={label}")
    return updated


def ensure_clean_before() -> None:
    result = subprocess.run(["git", "status", "--short"], cwd=ROOT, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        fail(result.stderr.strip())
    dirty = [line for line in result.stdout.splitlines() if line.strip()]
    if dirty:
        fail("working tree must be clean before migration: " + " | ".join(dirty))


def move_application() -> None:
    if RUNTIME_APPLICATION.is_file() and not LEGACY_APPLICATION.exists():
        print("ALREADY_MOVED=Opus/Runtime/Application.php")
    else:
        if not LEGACY_APPLICATION.is_file():
            fail("legacy application source missing")
        RUNTIME_APPLICATION.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(LEGACY_APPLICATION), str(RUNTIME_APPLICATION))
        print("MOVED=Opus/Legacy/Application/Application.class.php=>Opus/Runtime/Application.php")

    content = read(RUNTIME_APPLICATION)
    content = replace_once(
        content,
        "dirname(__DIR__, 3) . '/config/fsm.boot.php'",
        "dirname(__DIR__, 2) . '/config/fsm.boot.php'",
        "runtime_application_boot_fsm_root_depth",
    )
    write(RUNTIME_APPLICATION, content)


def remove_legacy_autoloader() -> None:
    if LEGACY_AUTOLOADER.exists():
        LEGACY_AUTOLOADER.unlink()
        print("REMOVED=Opus/Legacy/Autoload/autoloader.class.php")
    else:
        print("ALREADY_REMOVED=Opus/Legacy/Autoload/autoloader.class.php")

    for directory in [
        ROOT / "Opus/Legacy/Autoload",
        ROOT / "Opus/Legacy/Application",
        ROOT / "Opus/Legacy",
    ]:
        if directory.exists() and directory.is_dir():
            try:
                directory.rmdir()
                print(f"REMOVED_EMPTY_DIR={directory.relative_to(ROOT).as_posix()}")
            except OSError:
                print(f"DIR_NOT_EMPTY={directory.relative_to(ROOT).as_posix()}")


def patch_www_index() -> None:
    content = read(WWW_INDEX)
    content = replace_once(
        content,
        "require_once ROOT . '/Opus/Legacy/Autoload/autoloader.class.php';\n",
        "",
        "www_remove_legacy_autoloader_require",
    )
    content = replace_once(
        content,
        "require_once ROOT . '/Opus/Legacy/Application/Application.class.php';\n",
        "",
        "www_remove_legacy_application_require",
    )
    write(WWW_INDEX, content)


def patch_p5b_smoke() -> None:
    content = read(P5B_SMOKE)
    content = replace_once(
        content,
        " * - Legacy www/index.php explicitly loads Composer, legacy autoloader and legacy Application.",
        " * - www/index.php loads Composer and boots OPUS_Application from Composer classmap.",
        "p5b_doc_www_composer_only",
    )
    content = replace_once(
        content,
        " * - Legacy autoloader requires Composer-loaded Opus\\\\Runtime\\\\Bootstrap.",
        " * - Opus/Legacy is absent from runtime and must not be required by entrypoints.",
        "p5b_doc_legacy_removed",
    )
    content = replace_once(
        content,
        "        $this->checkLegacyEntrypoint();\n        $this->checkLegacyAutoloaderComposerGuard();\n        $this->checkBootstrapContract();\n        $this->checkLegacyApplicationContract();",
        "        $this->checkLegacyEntrypoint();\n        $this->checkLegacyRemoved();\n        $this->checkBootstrapContract();\n        $this->checkApplicationContract();",
        "p5b_run_sequence",
    )
    content = replace_once(
        content,
        "        $this->contains($content, \"require_once ROOT . '/Opus/Legacy/Autoload/autoloader.class.php';\", 'CHECK_WWW_REQUIRES_LEGACY_AUTOLOADER');\n        $this->contains($content, \"require_once ROOT . '/Opus/Legacy/Application/Application.class.php';\", 'CHECK_WWW_REQUIRES_LEGACY_APPLICATION');",
        "        $this->notContains($content, \"require_once ROOT . '/Opus/Legacy/Autoload/autoloader.class.php';\", 'CHECK_WWW_DOES_NOT_REQUIRE_LEGACY_AUTOLOADER');\n        $this->notContains($content, \"require_once ROOT . '/Opus/Legacy/Application/Application.class.php';\", 'CHECK_WWW_DOES_NOT_REQUIRE_LEGACY_APPLICATION');",
        "p5b_www_legacy_requires_removed",
    )
    content = regex_replace_once(
        content,
        r"    private function checkLegacyAutoloaderComposerGuard\(\): void\n    \{.*?    private function checkBootstrapContract",
        "    private function checkLegacyRemoved(): void\n    {\n        foreach ([\n            'Opus/Legacy',\n            'Opus/Legacy/Autoload/autoloader.class.php',\n            'Opus/Legacy/Application/Application.class.php',\n        ] as $path) {\n            $fullPath = $this->root . '/' . $path;\n            if (file_exists($fullPath)) {\n                $this->fail('CHECK_LEGACY_RUNTIME_PATH_ABSENT', $path);\n                return;\n            }\n        }\n        $this->ok('CHECK_LEGACY_RUNTIME_PATHS_ABSENT');\n    }\n\n    private function checkBootstrapContract",
        "p5b_replace_legacy_autoloader_check",
    )
    content = replace_once(
        content,
        "    private function checkLegacyApplicationContract(): void\n    {\n        $file = $this->root . '/Opus/Legacy/Application/Application.class.php';",
        "    private function checkApplicationContract(): void\n    {\n        $file = $this->root . '/Opus/Runtime/Application.php';",
        "p5b_application_contract_path",
    )
    content = replace_once(
        content,
        "        $this->contains($content, \"dirname(__DIR__, 3) . '/config/fsm.boot.php'\", 'CHECK_LEGACY_APPLICATION_BOOT_FSM_ROOT');\n        $this->notContains($content, \"dirname(__DIR__) . '/config/fsm.boot.php'\", 'CHECK_LEGACY_APPLICATION_NO_OLD_BOOT_FSM_ROOT');",
        "        $this->contains($content, \"dirname(__DIR__, 2) . '/config/fsm.boot.php'\", 'CHECK_RUNTIME_APPLICATION_BOOT_FSM_ROOT');\n        $this->notContains($content, \"dirname(__DIR__, 3) . '/config/fsm.boot.php'\", 'CHECK_RUNTIME_APPLICATION_NO_LEGACY_BOOT_FSM_ROOT');",
        "p5b_application_contract_tokens",
    )
    content = replace_once(
        content,
        "            'Opus/Legacy/Autoload/autoloader.class.php',\n            'Opus/Legacy/Application/Application.class.php',",
        "            'Opus/Runtime/Application.php',",
        "p5b_lint_runtime_application",
    )
    write(P5B_SMOKE, content)


def patch_p5e_audit() -> None:
    content = read(P5E_AUDIT)
    content = replace_once(
        content,
        "- keep modern and legacy entrypoints explicit;",
        "- keep modern and www entrypoints Composer-driven;",
        "p5e_doc_entrypoints",
    )
    content = replace_once(
        content,
        "EXPECTED_WWW_REQUIRES = [\n    \"$composerAutoload = ROOT . '/vendor/autoload.php';\",\n    \"throw new RuntimeException('OPUS_COMPOSER_AUTOLOAD_REQUIRED: ' . $composerAutoload);\",\n    \"require_once $composerAutoload;\",\n    \"require_once ROOT . '/Opus/Legacy/Autoload/autoloader.class.php';\",\n    \"require_once ROOT . '/Opus/Legacy/Application/Application.class.php';\",\n]",
        "EXPECTED_WWW_REQUIRES = [\n    \"$composerAutoload = ROOT . '/vendor/autoload.php';\",\n    \"throw new RuntimeException('OPUS_COMPOSER_AUTOLOAD_REQUIRED: ' . $composerAutoload);\",\n    \"require_once $composerAutoload;\",\n]\n\nFORBIDDEN_WWW_REQUIRES = [\n    \"require_once ROOT . '/Opus/Legacy/Autoload/autoloader.class.php';\",\n    \"require_once ROOT . '/Opus/Legacy/Application/Application.class.php';\",\n]",
        "p5e_expected_www_requires",
    )
    content = replace_once(
        content,
        "    ok(\"CHECK_LEGACY_WWW_EXPLICIT_REQUIRES\", str(len(EXPECTED_WWW_REQUIRES)))\n\n    if \"OPUS_Application::getInstance()\" not in content or \"$app->run();\" not in content:",
        "    ok(\"CHECK_WWW_COMPOSER_REQUIRES\", str(len(EXPECTED_WWW_REQUIRES)))\n\n    for token in FORBIDDEN_WWW_REQUIRES:\n        if token in content:\n            return fail(\"CHECK_WWW_FORBIDDEN_LEGACY_REQUIRE\", token)\n    ok(\"CHECK_WWW_LEGACY_REQUIRES_ABSENT\")\n\n    if \"OPUS_Application::getInstance()\" not in content or \"$app->run();\" not in content:",
        "p5e_forbidden_www_requires",
    )
    content = replace_once(
        content,
        "    print(\"SCOPE=stable bootstrap runtime boundary, modern entrypoint, legacy entrypoint, composer autoload\")",
        "    print(\"SCOPE=stable bootstrap runtime boundary, modern entrypoint, www composer entrypoint\")",
        "p5e_scope",
    )
    write(P5E_AUDIT, content)


def patch_p5g_audit() -> None:
    content = '''#!/usr/bin/env python3
"""
P5G_LEGACY_AUTOLOADER_BOOTSTRAP_BRIDGE_AUDIT

Read-only audit for the removed legacy autoloader boundary.

Purpose:
- prove that www/index.php is Composer-only before OPUS_Application boot;
- prove that the legacy DirectoriesAutoloader runtime file is absent;
- prove that Opus/Legacy does not participate in runtime loading anymore;
- never rewrite source, caches, Composer output, or entrypoints.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

PATCH_ID = "P5G_LEGACY_AUTOLOADER_BOOTSTRAP_BRIDGE_AUDIT"
ROOT = Path.cwd()
WWW_INDEX = "www/index.php"
RUNTIME_APPLICATION = "Opus/Runtime/Application.php"
LEGACY_ROOT = "Opus/Legacy"
LEGACY_AUTOLOADER = "Opus/Legacy/Autoload/autoloader.class.php"
LEGACY_APPLICATION = "Opus/Legacy/Application/Application.class.php"

WWW_COMPOSER_TOKENS = [
    "$composerAutoload = ROOT . '/vendor/autoload.php';",
    "throw new RuntimeException('OPUS_COMPOSER_AUTOLOAD_REQUIRED: ' . $composerAutoload);",
    "require_once $composerAutoload;",
]

WWW_FORBIDDEN_TOKENS = [
    "require_once ROOT . '/Opus/Legacy/Autoload/autoloader.class.php';",
    "require_once ROOT . '/Opus/Legacy/Application/Application.class.php';",
    "require_once ROOT . '/Opus/Bootstrap.php';",
]


def fail(code: str, detail: str = "") -> int:
    print(f"{code}=FAIL" + (f" {detail}" if detail else ""))
    return 1


def ok(code: str, detail: str = "") -> None:
    print(f"{code}=OK" + (f" {detail}" if detail else ""))


def run_git(args: list[str]) -> list[str]:
    result = subprocess.run(["git", *args], cwd=ROOT, text=True, capture_output=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8", errors="ignore")


def php_lint(rel: str) -> bool:
    result = subprocess.run(["php", "-l", rel], cwd=ROOT, text=True, capture_output=True, check=False)
    if result.returncode == 0:
        ok(f"CHECK_PHP_LINT_{rel.upper().replace('/', '_').replace('.', '_')}")
        return True
    if result.stdout.strip():
        print(result.stdout.strip())
    if result.stderr.strip():
        print(result.stderr.strip())
    return False


def check_required_files() -> int:
    missing = [rel for rel in [WWW_INDEX, RUNTIME_APPLICATION, "vendor/autoload.php"] if not (ROOT / rel).is_file()]
    if missing:
        return fail("CHECK_REQUIRED_FILES", ",".join(missing))
    ok("CHECK_REQUIRED_FILES")
    return 0


def check_legacy_files_absent() -> int:
    existing = [rel for rel in [LEGACY_AUTOLOADER, LEGACY_APPLICATION, LEGACY_ROOT] if (ROOT / rel).exists()]
    if existing:
        return fail("CHECK_LEGACY_RUNTIME_PATHS_ABSENT", ",".join(existing))
    ok("CHECK_LEGACY_RUNTIME_PATHS_ABSENT")
    return 0


def check_www_composer_only_entrypoint() -> int:
    content = read(WWW_INDEX)
    for token in WWW_COMPOSER_TOKENS:
        if token not in content:
            return fail("CHECK_WWW_COMPOSER_TOKEN", token)
    for token in WWW_FORBIDDEN_TOKENS:
        if token in content:
            return fail("CHECK_WWW_FORBIDDEN_LEGACY_TOKEN", token)
    if "OPUS_Application::getInstance()" not in content or "$app->run();" not in content:
        return fail("CHECK_WWW_APPLICATION_BOOT_SEQUENCE", WWW_INDEX)
    ok("CHECK_WWW_COMPOSER_ONLY_ENTRYPOINT")
    if not php_lint(WWW_INDEX):
        return fail("CHECK_WWW_PHP_LINT", WWW_INDEX)
    return 0


def check_runtime_application_contract() -> int:
    content = read(RUNTIME_APPLICATION)
    required = [
        "class OPUS_Application",
        "dirname(__DIR__, 2) . '/config/fsm.boot.php'",
    ]
    for token in required:
        if token not in content:
            return fail("CHECK_RUNTIME_APPLICATION_TOKEN", token)
    if "dirname(__DIR__, 3) . '/config/fsm.boot.php'" in content:
        return fail("CHECK_RUNTIME_APPLICATION_NO_LEGACY_BOOT_FSM_ROOT")
    ok("CHECK_RUNTIME_APPLICATION_CONTRACT")
    if not php_lint(RUNTIME_APPLICATION):
        return fail("CHECK_RUNTIME_APPLICATION_PHP_LINT", RUNTIME_APPLICATION)
    return 0


def scan_legacy_runtime_refs() -> int:
    files = run_git(["ls-files"])
    runtime_refs: list[str] = []
    ignored_refs: list[str] = []
    for rel in files:
        if not rel.endswith((".php", ".py", ".md", ".json", ".cmd")):
            continue
        if rel.startswith(("vendor/", "var/", "tmp/")):
            continue
        try:
            content = read(rel)
        except OSError:
            continue
        has_legacy_ref = "Opus/Legacy" in content or "DirectoriesAutoloader" in content
        if not has_legacy_ref:
            continue
        if rel == WWW_INDEX or rel.startswith("Opus/"):
            runtime_refs.append(rel)
        else:
            ignored_refs.append(rel)

    print("LEGACY_REFERENCE_CLASSIFICATION")
    for rel in sorted(runtime_refs):
        print(f"RUNTIME_LEGACY_REF={rel}")
    for rel in sorted(ignored_refs):
        print(f"NON_RUNTIME_LEGACY_REF={rel}")

    if runtime_refs:
        return fail("CHECK_LEGACY_RUNTIME_REFERENCES", ",".join(sorted(runtime_refs)))
    ok("CHECK_LEGACY_RUNTIME_REFERENCES", "none")
    return 0


def print_decision() -> None:
    print()
    print("P5G_LEGACY_AUTOLOADER_REMOVAL_DECISION")
    print("WWW_ENTRYPOINT_COMPOSER_ONLY=YES")
    print("LEGACY_AUTOLOADER_RUNTIME_FILE_PRESENT=NO")
    print("RUNTIME_APPLICATION_LOCATION=Opus/Runtime/Application.php")
    print("DECISION=LEGACY_RUNTIME_BOUNDARY_REMOVED")
    print("NEXT_SAFE_STEP=P6B_ARCHIVE_P6A_MIGRATION_OR_REMOVE_STALE_LEGACY_AUDITS")


def main() -> int:
    print(PATCH_ID)
    print("MODE=READ_ONLY")
    print("SCOPE=removed legacy autoloader runtime boundary")

    checks = [
        check_required_files(),
        check_legacy_files_absent(),
        check_www_composer_only_entrypoint(),
        check_runtime_application_contract(),
        scan_legacy_runtime_refs(),
    ]
    if any(code != 0 for code in checks):
        print(f"{PATCH_ID}_FAIL")
        return 1

    print_decision()
    print(f"{PATCH_ID}_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''
    write(P5G_AUDIT, content)
    print("REWRITTEN=tools/audits/audit_p5g_legacy_autoloader_bootstrap_bridge.py")


def patch_p5h_audit() -> None:
    content = read(P5H_AUDIT)
    content = replace_once(content, 'LEGACY_AUTOLOADER = "Opus/Legacy/Autoload/autoloader.class.php"\n', '', 'p5h_remove_legacy_autoloader_constant')
    content = replace_once(
        content,
        "RUNTIME_FILES = {\n    MODERN_INDEX,\n    WWW_INDEX,\n    LEGACY_AUTOLOADER,\n}",
        "RUNTIME_FILES = {\n    MODERN_INDEX,\n    WWW_INDEX,\n}",
        "p5h_runtime_files_without_legacy",
    )
    content = replace_once(
        content,
        "    \"Opus/Runtime/Kernel.php\",\n    LEGACY_AUTOLOADER,\n    WWW_INDEX,",
        "    \"Opus/Runtime/Kernel.php\",\n    WWW_INDEX,",
        "p5h_required_files_without_legacy",
    )
    content = regex_replace_once(
        content,
        r"def check_legacy_guard_ready_for_target_update\(\) -> int:\n.*?\n\ndef scan_class_and_path_references",
        "def check_legacy_runtime_absent() -> int:\n    existing = [rel for rel in [\"Opus/Legacy\", \"Opus/Legacy/Autoload/autoloader.class.php\", \"Opus/Legacy/Application/Application.class.php\"] if (ROOT / rel).exists()]\n    if existing:\n        return fail(\"CHECK_LEGACY_RUNTIME_PATHS_ABSENT\", \",\".join(existing))\n    ok(\"CHECK_LEGACY_RUNTIME_PATHS_ABSENT\")\n    return 0\n\n\ndef scan_class_and_path_references",
        "p5h_replace_legacy_guard_check",
    )
    content = replace_once(
        content,
        "        check_legacy_guard_ready_for_target_update(),",
        "        check_legacy_runtime_absent(),",
        "p5h_check_sequence",
    )
    content = replace_once(
        content,
        "    print(\"LEGACY_GUARD_USES_RUNTIME_BOOTSTRAP=YES\")",
        "    print(\"LEGACY_RUNTIME_BOUNDARY_PRESENT=NO\")",
        "p5h_decision_legacy_removed",
    )
    content = replace_once(
        content,
        "    print(\"NEXT_SAFE_STEP=P6A_SELECT_NEXT_RUNTIME_CLEANUP_TARGET\")",
        "    print(\"NEXT_SAFE_STEP=P6B_ARCHIVE_P6A_MIGRATION_OR_REMOVE_STALE_LEGACY_AUDITS\")",
        "p5h_next_step",
    )
    write(P5H_AUDIT, content)


def verify_no_active_legacy_runtime_refs() -> None:
    runtime_files = [WWW_INDEX, ROOT / "index.php"] + list((ROOT / "Opus").rglob("*.php"))
    offenders: list[str] = []
    for path in runtime_files:
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT).as_posix()
        content = path.read_text(encoding="utf-8", errors="ignore")
        if "Opus/Legacy" in content or "DirectoriesAutoloader" in content:
            offenders.append(rel)
    if offenders:
        fail("active runtime legacy references remain: " + ",".join(offenders))
    print("CHECK_ACTIVE_RUNTIME_LEGACY_REFERENCES=OK none")


def main() -> int:
    print(f"== {PATCH_ID} ==")
    ensure_clean_before()
    move_application()
    remove_legacy_autoloader()
    patch_www_index()
    patch_p5b_smoke()
    patch_p5e_audit()
    patch_p5g_audit()
    patch_p5h_audit()
    verify_no_active_legacy_runtime_refs()
    print("COMPOSER_DUMP_AUTOLOAD_REQUIRED=YES")
    print(f"{PATCH_ID}_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
