<?php declare(strict_types=1);
function p7np_e(mixed $v):string{if(is_array($v)){$v=json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'';}if(is_bool($v)){$v=$v?'true':'false';}if($v===null){$v='null';}return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function p7np_id(array $o):string{return (string)($o['operation_id']??$o['id']??'');}
$r=dirname(__DIR__,3);require $r.'/vendor/autoload.php';
$site=(string)($_GET['site']??'site-alpha');
$f=new \OpusLstsarManager\View\LstsarManagerViewModelFactory();$c=new \OpusLstsarManager\Controller\OperationsController($f);$vm=$c->operations($site);
$d=is_array($vm['operations_dashboard']??null)?$vm['operations_dashboard']:[];$cnt=is_array($d['counters']??null)?$d['counters']:[];$ops=is_array($d['operations']??null)?$d['operations']:[];
$first=is_array($ops[0]??null)?$ops[0]:[];$firstId=p7np_id($first);
$diag=['contract'=>'P7_OPS_NAVIGATION_POLISH_CORE','routes'=>['/opus-lstsar-manager','/opus-lstsar-manager/operations','/opus-lstsar-manager/command','/opus-lstsar-manager/command-center','/opus-lstsar-manager/navigation','/opus-lstsar-manager/navigation-polish','/opus-lstsar-manager/action'],'operation_count'=>count($ops),'side_effects'=>false];
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><title>OPUS OPS Navigation Polish</title><link rel="stylesheet" href="/ops-ui.css" data-contract="P7_OPS_NAVIGATION_POLISH_CORE"></head><body><main>
<nav class="ops-main-nav p7-ops-navigation-polish" data-contract="P7_OPS_NAVIGATION_POLISH_CORE"><a href="/opus-lstsar-manager?site=<?=p7np_e($site)?>">Dashboard</a><a href="/opus-lstsar-manager/operations?site=<?=p7np_e($site)?>">Operations</a><a href="/opus-lstsar-manager/command?site=<?=p7np_e($site)?>">Command Center</a><a href="/opus-lstsar-manager/navigation?site=<?=p7np_e($site)?>">Navigation</a><?php if($firstId!==''):?><a href="/opus-lstsar-manager/action?site=<?=p7np_e($site)?>&operation=<?=p7np_e($firstId)?>&action=preview">Actions</a><?php endif;?><a href="/opus-lstsar-manager/diagnostics?site=site-alpha">Diagnostics</a><a href="/opus-lstsar-manager/health?site=site-alpha">Health Hub</a></nav>
<section class="panel"><h1>OPUS OPS Navigation Polish</h1><p><span class="ops-badge">P7_OPS_NAVIGATION_POLISH_CORE</span></p><div class="grid"><div class="card"><strong><?=p7np_e($cnt['operations']??count($ops))?></strong>Operations</div><div class="card"><strong><?=p7np_e($cnt['active']??0)?></strong>Active</div><div class="card"><strong><?=p7np_e($cnt['ready']??0)?></strong>Ready</div><div class="card"><strong><?=p7np_e($cnt['blocked']??0)?></strong>Blocked</div></div></section>
<section class="panel"><h2>Navigation unifiée</h2><p>Dashboard, Operations, Command Center, Navigation et Actions utilisent maintenant les mêmes routes OPS locales.</p></section>
<section class="panel"><h2>Operations table</h2><div class="ops-table-wrap"><table class="ops-polished-table"><tr><th>Operation</th><th>Status</th><th>Actions</th></tr><?php foreach($ops as $op): if(!is_array($op))continue; $id=p7np_id($op); $st=(string)($op['status']??(($op['ready']??false)?'ready':'unknown'));?><tr><td><code><?=p7np_e($id)?></code></td><td><span class="ops-badge"><?=p7np_e($st)?></span></td><td><div class="ops-action-cluster"><a class="ops-action-link" href="/opus-lstsar-manager/action?site=<?=p7np_e($site)?>&operation=<?=p7np_e($id)?>&action=preview">Preview</a><a class="ops-action-link" href="/opus-lstsar-manager/action?site=<?=p7np_e($site)?>&operation=<?=p7np_e($id)?>&action=dry-run">Dry-run</a><a class="ops-action-link" href="/opus-lstsar-manager/action?site=<?=p7np_e($site)?>&operation=<?=p7np_e($id)?>&action=audit">Audit</a></div></td></tr><?php endforeach;?></table></div></section>
<section class="panel"><h2>Diagnostics</h2><pre><?=p7np_e(json_encode($diag,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'{}')?></pre></section>
</main></body></html>
