<?php
declare(strict_types=1);
require_once __DIR__ . '/language.php';
p7ops_clean_session_start_once();
$history = p7ops_clean_profiler_history();
$current = $history !== [] ? $history[array_key_last($history)] : p7ops_clean_profiler_collect('page');
$e = static fn(string $v): string => p7ops_clean_h($v);
$kv = static function(array $rows) use ($e): string {
    $o = '<dl class="opf-kv">';
    foreach ($rows as $k=>$v) { $o .= '<dt>'.$e((string)$k).'</dt><dd>'.$e((string)$v).'</dd>'; }
    return $o.'</dl>';
};
$chain = '<ol class="opf-chain">';
foreach (p7ops_clean_chain_steps() as $s) {
    $chain .= '<li><a href="'.$e((string)$s['route']).'"><span>'.$e((string)$s['n']).'</span><strong>'.$e((string)$s['title']).'</strong><em>'.$e((string)$s['text']).'</em></a></li>';
}
$chain .= '</ol>';
$hist = '<table><thead><tr><th>Token</th><th>Method</th><th>URI</th><th>Status</th><th>Time</th></tr></thead><tbody>';
foreach (array_reverse($history) as $r) {
    $hist .= '<tr><td><code>'.$e((string)($r['token']??'')).'</code></td><td>'.$e((string)($r['method']??'')).'</td><td><code>'.$e((string)($r['uri']??'')).'</code></td><td>'.$e((string)($r['status']??'')).'</td><td>'.$e((string)($r['duration_ms']??'')).' ms</td></tr>';
}
$hist .= '</tbody></table>';
?><!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OPUS Web Profiler</title><link rel="stylesheet" href="/ops-ui.css"><style>
body{margin:0;background:#0b1220;color:#f8fafc;font:15px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.opf{width:min(1280px,calc(100vw - 2rem));margin:0 auto;padding:1rem 1rem 5rem}.hero,.panel{border:1px solid rgba(96,165,250,.35);border-radius:18px;background:#111827;padding:1rem;margin:1rem 0}.hero{display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap}.hero h1{font-size:clamp(2rem,4vw,4rem);margin:.2rem 0}.actions,.tabs{display:flex;flex-wrap:wrap;gap:.5rem}.actions a,.tabs a{border:1px solid rgba(34,211,238,.45);border-radius:999px;padding:.55rem .85rem;color:#f8fafc;text-decoration:none;background:#020617;font-weight:800}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(22rem,1fr));gap:1rem}.opf-kv{display:grid;grid-template-columns:minmax(8rem,auto) minmax(0,1fr);gap:.55rem .85rem}.opf-kv dt{color:#67e8f9;font-weight:900}.opf-kv dd{margin:0;overflow-wrap:anywhere}.opf-chain{display:grid;grid-template-columns:repeat(auto-fit,minmax(19rem,1fr));gap:.75rem;padding:0;list-style:none}.opf-chain a{display:grid;grid-template-columns:auto minmax(0,1fr);gap:.5rem .75rem;border:1px solid rgba(34,211,238,.35);border-radius:14px;padding:.8rem;text-decoration:none;color:#f8fafc;background:#020617}.opf-chain span{grid-row:1/3;display:grid;place-items:center;width:2.4rem;height:2.4rem;border-radius:999px;background:#155e75;color:#67e8f9;font-weight:950}.opf-chain em{font-style:normal;color:#cbd5e1}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid rgba(96,165,250,.25);padding:.65rem;text-align:left;vertical-align:top}code{white-space:nowrap}.scroll{overflow:auto}@media(max-width:800px){.grid{grid-template-columns:1fr}.opf-kv{grid-template-columns:1fr}}
</style></head><body><main class="opf" data-contract="P7_OPS_PROFILER_CHAIN_CLEANUP_CORE"><section class="hero"><div><p><strong>OPUS OPS</strong> · profiler typé session</p><h1>OPUS Web Profiler</h1><p><code>profiler=1</code> active le mode profiler en SESSION jusqu’à sortie explicite.</p></div><nav class="actions"><a href="/opus-lstsar-manager?site=site-alpha&lang=fr&profiler=1">Enable</a><a href="/opus-lstsar-manager/profiler/exit">Exit profiler</a><a href="/opus-lstsar-manager/chain">OPS Chain</a><a href="/opus-lstsar-manager/operations">Operations</a></nav></section><nav class="tabs"><a href="#request">Request</a><a href="#performance">Performance</a><a href="#session">Session</a><a href="#auth">Auth / SSO</a><a href="#chain">Chain</a><a href="#logs">Logs</a><a href="#history">History</a></nav><section class="grid"><article id="request" class="panel"><h2>Request</h2><?= $kv(['Token'=>$current['token']??'','Method'=>$current['method']??'','URI'=>$current['uri']??'','Path'=>$current['path']??'','Query'=>$current['query']??'','Remote address'=>$current['remote_addr']??'']) ?></article><article id="performance" class="panel"><h2>Performance</h2><?= $kv(['Status'=>$current['status']??'','Duration'=>(string)($current['duration_ms']??'').' ms','Peak memory'=>(string)($current['memory_peak_bytes']??'').' bytes','Current memory'=>(string)($current['memory_current_bytes']??'').' bytes']) ?></article><article id="session" class="panel"><h2>Session</h2><?= $kv(['Profiler mode'=>$current['session_profiler']??'','Persistence key'=>'$_SESSION[p7ops_clean_profiler_enabled]','Exit route'=>'/opus-lstsar-manager/profiler/exit']) ?></article><article id="auth" class="panel"><h2>Auth / SSO</h2><?= $kv(['User'=>$current['user']??'','Roles'=>$current['roles']??'','Environment'=>$current['environment']??'','SSO'=>((p7ops_config()['sso']['enabled']??false)?'enabled':'disabled')]) ?></article></section><section id="chain" class="panel"><h2>Chaîne fonctionnelle complète</h2><?= $chain ?></section><section id="logs" class="panel"><h2>Logs</h2><?= $kv(['Access'=>'var/logs/opus_lstsar-manager/access.log','Auth'=>'var/logs/opus_lstsar-manager/auth.log','Profiler'=>'var/logs/opus_lstsar-manager/profiler.log','PHP server'=>'var/logs/opus_lstsar-manager/php-server.log']) ?></section><section id="history" class="panel"><h2>History</h2><div class="scroll"><?= $hist ?></div></section></main></body></html>