@echo off
setlocal EnableExtensions
set "OPUS_RECIPE_OPEN_BROWSER=1"
set "OPUS_RECIPE_BROWSER_HOLD_SECONDS=1"
set "OPUS_RECIPE_BROWSER_FINAL_HOLD_SECONDS=10"
call "%~dp0RUN_OPUS_FULL_RECIPE.cmd"
exit /b %ERRORLEVEL%
