<?php
declare(strict_types=1);

namespace OpusRefBook\Reference\Service;

/**
 * PUBLIC SERVICE
 *
 * Role:
 *   Build the installed / shared / official version read-model displayed by
 *   OPUS_REF_BOOK.
 *
 * Contract:
 *   Read-only service. It never fetches the network during page rendering.
 *   Official GitHub data must come from the cached JSON registry generated by
 *   a separate maintenance script.
 */
final class ReferenceVersionService
{
    public function __construct(private readonly string $appRoot)
    {
    }

    /**
     * @return array<string,mixed>
     */
    public function panel(): array
    {
        $composer = $this->readJson($this->appRoot . '/composer.json');
        $official = $this->readJson($this->appRoot . '/var/version/official_versions.json');
        $git = $this->localGitState();
        $shared = $this->sharedFrameworkState($composer);

        return [
            'schema' => 'OPUS_REFBOOK_VERSION_PANEL_V1',
            'installed' => [
                'application' => basename($this->appRoot) ?: 'OPUS_REF_BOOK',
                'package_name' => (string) ($composer['name'] ?? 'logandplay/opus-ref-book'),
                'package_version' => (string) ($composer['version'] ?? 'dev-' . ($git['branch'] ?? 'main')),
                'branch' => $git['branch'],
                'commit' => $git['commit'],
                'commit_short' => $git['commit_short'],
                'state' => $git['dirty'] === true ? 'dirty' : ($git['dirty'] === false ? 'clean' : 'unknown'),
                'remote' => $git['remote'],
            ],
            'shared' => $shared,
            'official' => [
                'repository' => (string) ($official['repository'] ?? 'philstephibanez-wq/OPUS_REF_BOOK'),
                'default_branch' => (string) ($official['default_branch'] ?? 'main'),
                'default_branch_commit' => (string) ($official['default_branch_commit'] ?? ''),
                'default_branch_commit_short' => $this->shortSha((string) ($official['default_branch_commit'] ?? '')),
                'latest_tag' => $official['latest_tag'] ?? null,
                'latest_release' => $official['latest_release'] ?? null,
                'fetched_at' => (string) ($official['fetched_at'] ?? ''),
                'source' => (string) ($official['source'] ?? 'cache'),
                'available' => ($official !== []),
            ],
        ];
    }

    /**
     * @return array<string,mixed>
     */
    private function sharedFrameworkState(array $composer): array
    {
        $requires = is_array($composer['require'] ?? null) ? $composer['require'] : [];
        $repositories = is_array($composer['repositories'] ?? null) ? $composer['repositories'] : [];

        $pathRepository = '';
        foreach ($repositories as $repository) {
            if (!is_array($repository)) {
                continue;
            }

            if (($repository['type'] ?? null) === 'path') {
                $pathRepository = (string) ($repository['url'] ?? '');
                break;
            }
        }

        $resolvedRoot = $pathRepository !== '' ? $this->normalizePath($pathRepository) : '';
        $sharedGit = is_dir($resolvedRoot) ? (new self($resolvedRoot))->localGitState() : [
            'branch' => null,
            'commit' => null,
            'commit_short' => null,
            'dirty' => null,
            'remote' => null,
        ];

        return [
            'package_name' => 'logandplay/opus',
            'constraint' => (string) ($requires['logandplay/opus'] ?? ''),
            'repository_type' => $pathRepository !== '' ? 'path' : 'composer',
            'repository_path' => $resolvedRoot,
            'present' => $resolvedRoot !== '' && is_dir($resolvedRoot),
            'branch' => $sharedGit['branch'],
            'commit' => $sharedGit['commit'],
            'commit_short' => $sharedGit['commit_short'],
            'state' => $sharedGit['dirty'] === true ? 'dirty' : ($sharedGit['dirty'] === false ? 'clean' : 'unknown'),
            'remote' => $sharedGit['remote'],
        ];
    }

    /**
     * @return array{branch:?string,commit:?string,commit_short:?string,dirty:?bool,remote:?string}
     */
    private function localGitState(): array
    {
        $gitDir = $this->gitDirectory();
        $branch = null;
        $commit = null;
        $remote = null;

        if ($gitDir !== null) {
            $head = $this->readText($gitDir . '/HEAD');
            if (str_starts_with($head, 'ref: ')) {
                $ref = trim(substr($head, 5));
                $branch = str_starts_with($ref, 'refs/heads/') ? substr($ref, 11) : $ref;
                $commit = $this->readText($gitDir . '/' . $ref);
                if ($commit === '') {
                    $commit = $this->packedRef($gitDir, $ref);
                }
            } elseif ($head !== '') {
                $commit = $head;
                $branch = 'detached';
            }

            $remote = $this->originUrl($gitDir . '/config');
        }

        if ($commit === null || $commit === '') {
            $commit = $this->runGit('rev-parse HEAD');
        }

        if ($branch === null || $branch === '') {
            $branch = $this->runGit('rev-parse --abbrev-ref HEAD');
        }

        if ($remote === null || $remote === '') {
            $remote = $this->runGit('config --get remote.origin.url');
        }

        $dirty = null;
        $status = $this->runGit('status --porcelain');
        if ($status !== null) {
            $dirty = trim($status) !== '';
        }

        $commit = $commit !== null && $commit !== '' ? trim($commit) : null;

        return [
            'branch' => $branch !== null && $branch !== '' ? trim($branch) : null,
            'commit' => $commit,
            'commit_short' => $commit !== null ? $this->shortSha($commit) : null,
            'dirty' => $dirty,
            'remote' => $remote !== null && $remote !== '' ? trim($remote) : null,
        ];
    }

    private function gitDirectory(): ?string
    {
        $git = $this->appRoot . '/.git';
        if (is_dir($git)) {
            return $git;
        }

        if (is_file($git)) {
            $content = $this->readText($git);
            if (str_starts_with($content, 'gitdir:')) {
                $dir = trim(substr($content, 7));
                if ($dir !== '') {
                    return $this->normalizePath($dir, dirname($git));
                }
            }
        }

        return null;
    }

    private function packedRef(string $gitDir, string $ref): string
    {
        $packed = $this->readText($gitDir . '/packed-refs');
        foreach (preg_split('/\R/', $packed) ?: [] as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#') || str_starts_with($line, '^')) {
                continue;
            }

            [$sha, $name] = array_pad(preg_split('/\s+/', $line, 2) ?: [], 2, '');
            if ($name === $ref) {
                return $sha;
            }
        }

        return '';
    }

    private function originUrl(string $configPath): ?string
    {
        $config = $this->readText($configPath);
        $inOrigin = false;

        foreach (preg_split('/\R/', $config) ?: [] as $line) {
            $trimmed = trim($line);
            if ($trimmed === '[remote "origin"]') {
                $inOrigin = true;
                continue;
            }

            if ($trimmed !== '' && str_starts_with($trimmed, '[')) {
                $inOrigin = false;
            }

            if ($inOrigin && str_starts_with($trimmed, 'url =')) {
                return trim(substr($trimmed, 5));
            }
        }

        return null;
    }

    private function runGit(string $arguments): ?string
    {
        if (!function_exists('shell_exec')) {
            return null;
        }

        $command = 'git -C ' . escapeshellarg($this->appRoot) . ' ' . $arguments . ' 2>&1';
        $output = shell_exec($command);
        if (!is_string($output)) {
            return null;
        }

        $output = trim($output);
        if ($output === '' || str_contains(strtolower($output), 'fatal:')) {
            return null;
        }

        return $output;
    }

    /**
     * @return array<string,mixed>
     */
    private function readJson(string $path): array
    {
        if (!is_file($path)) {
            return [];
        }

        $content = file_get_contents($path);
        if (!is_string($content) || trim($content) === '') {
            return [];
        }

        $decoded = json_decode($content, true);
        return is_array($decoded) ? $decoded : [];
    }

    private function readText(string $path): string
    {
        if (!is_file($path)) {
            return '';
        }

        $content = file_get_contents($path);
        return is_string($content) ? trim($content) : '';
    }

    private function normalizePath(string $path, ?string $base = null): string
    {
        $path = str_replace('\\', '/', $path);
        if ($base !== null && !preg_match('/^[A-Za-z]:\//', $path) && !str_starts_with($path, '/')) {
            $path = rtrim(str_replace('\\', '/', $base), '/') . '/' . $path;
        }

        $real = realpath($path);
        return $real !== false ? str_replace('\\', '/', $real) : $path;
    }

    private function shortSha(string $sha): string
    {
        return $sha !== '' ? substr($sha, 0, 7) : '';
    }
}
