<?php
declare(strict_types=1);

return [
    'fr' => [
        '' => 'home',
        'framework' => 'framework',
        'router' => 'router',
        'packages' => 'packages',
        'controllers' => 'controllers',
        'views' => 'views',
        'templates' => 'templates',
        'models-db' => 'models',
        'fsm' => 'fsm',
        'acl' => 'acl',
        'rest' => 'rest',
        'i18n' => 'i18n',
        'démo-interne' => 'accented',
        'debug-logs' => 'debug_logs',
        'mailpit' => 'mailpit',
        'articles' => 'articles',
        'galerie' => 'gallery',
        'contact' => 'contact',
    ],
    'en' => [
        '' => 'home',
        'framework' => 'framework',
        'router' => 'router',
        'packages' => 'packages',
        'controllers' => 'controllers',
        'views' => 'views',
        'templates' => 'templates',
        'models-db' => 'models',
        'fsm' => 'fsm',
        'acl' => 'acl',
        'rest' => 'rest',
        'i18n' => 'i18n',
        'internal-demo' => 'accented',
        'debug-logs' => 'debug_logs',
        'mailpit' => 'mailpit',
        'articles' => 'articles',
        'gallery' => 'gallery',
        'contact' => 'contact',
    ],
    'es' => [
        '' => 'home',
        'arquitectura' => 'framework',
        'router' => 'router',
        'paquetes' => 'packages',
        'controladores' => 'controllers',
        'vistas' => 'views',
        'plantillas' => 'templates',
        'modelos-db' => 'models',
        'fsm' => 'fsm',
        'acl' => 'acl',
        'rest' => 'rest',
        'i18n' => 'i18n',
        'demo-interna' => 'accented',
        'debug-logs' => 'debug_logs',
        'mailpit' => 'mailpit',
        'articulos' => 'articles',
        'galeria' => 'gallery',
        'contacto' => 'contact',
    ],
];
