<?php declare(strict_types=1);
$lines=['P7_OPS_NAVIGATION_POLISH_CORE_SMOKE'];$root=dirname(__DIR__,2);
$files=['index'=>$root.'/sites/opus-p7-ops/public/index.php','router'=>$root.'/sites/opus-p7-ops/public/router.php','action'=>$root.'/sites/opus-p7-ops/public/action.php','command'=>$root.'/sites/opus-p7-ops/public/command.php','navigation'=>$root.'/sites/opus-p7-ops/public/navigation.php','css'=>$root.'/sites/opus-p7-ops/public/ops-ui.css','readme'=>$root.'/sites/opus-p7-ops/README.md'];
$all='';foreach($files as $f){if(!is_file($f)){throw new RuntimeException('NAV_POLISH_FILE_MISSING: '.$f);}$s=file_get_contents($f);if($s===false){throw new RuntimeException('NAV_POLISH_READ_FAILED: '.$f);}$all.=$s."\n";}
foreach(['P7_OPS_NAVIGATION_POLISH_CORE','/opus-lstsar-manager/navigation','/opus-lstsar-manager/navigation-polish','/opus-lstsar-manager/command','/opus-lstsar-manager/action','ops-main-nav','ops-polished-table','ops-action-cluster','Dashboard','Operations','Command Center','Navigation','Preview','Dry-run','Audit','side_effects'] as $m){if(!str_contains($all,$m)){throw new RuntimeException('NAV_POLISH_MARKER_MISSING: '.$m);}}
$lines[]='CHECK_P7_OPS_NAVIGATION_POLISH_MARKERS=OK';
require $root.'/vendor/autoload.php';$f=new \OpusLstsarManager\View\LstsarManagerViewModelFactory();$c=new \OpusLstsarManager\Controller\OperationsController($f);$vm=$c->operations('site-alpha');$d=is_array($vm['operations_dashboard']??null)?$vm['operations_dashboard']:[];$ops=is_array($d['operations']??null)?$d['operations']:[];$first=is_array($ops[0]??null)?$ops[0]:null;if($first===null){throw new RuntimeException('NAV_POLISH_NO_OPERATION');}$id=(string)($first['operation_id']??$first['id']??'');if($id===''){throw new RuntimeException('NAV_POLISH_EMPTY_OPERATION_ID');}
$_SERVER['REQUEST_URI']='/opus-lstsar-manager/navigation?site=site-alpha';$_GET=['site'=>'site-alpha'];ob_start();require $files['navigation'];$html=(string)ob_get_clean();http_response_code(200);
foreach(['OPUS OPS Navigation Polish','P7_OPS_NAVIGATION_POLISH_CORE','Navigation unifiée','Operations table','Diagnostics',$id,'ops-action-link','Preview','Dry-run','Audit','side_effects','false'] as $m){if(!str_contains($html,$m)){throw new RuntimeException('NAV_POLISH_RENDER_MARKER_MISSING: '.$m);}}
$lines[]='CHECK_P7_OPS_NAVIGATION_POLISH_RENDER=OK';
$router=file_get_contents($files['router']);if($router===false){throw new RuntimeException('NAV_POLISH_ROUTER_READ_FAILED');}
foreach(['/opus-lstsar-manager/navigation','/opus-lstsar-manager/navigation-polish','/opus-lstsar-manager/command','/opus-lstsar-manager/action'] as $route){if(!str_contains($router,$route)){throw new RuntimeException('NAV_POLISH_ROUTER_MARKER_MISSING: '.$route);}}
$lines[]='CHECK_P7_OPS_NAVIGATION_POLISH_ROUTER=OK';$lines[]='P7_OPS_NAVIGATION_POLISH_CORE_SMOKE_OK';echo implode(PHP_EOL,$lines).PHP_EOL;
